//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TirsvadCLI.PfxCertificate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TirsvadCLI.PfxCertificate.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate added to.
        /// </summary>
        internal static string Certificate_added_to {
            get {
                return ResourceManager.GetString("Certificate added to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate created successfully.
        /// </summary>
        internal static string Certificate_created_successfully {
            get {
                return ResourceManager.GetString("Certificate created successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Details.
        /// </summary>
        internal static string Certificate_details {
            get {
                return ResourceManager.GetString("Certificate details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate loaded successfully.
        /// </summary>
        internal static string Certificate_loaded_successfully {
            get {
                return ResourceManager.GetString("Certificate loaded successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate removal is only supported on Windows.
        /// </summary>
        internal static string Certificate_removal_is_only_supported_on_Windows {
            get {
                return ResourceManager.GetString("Certificate removal is only supported on Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common name.
        /// </summary>
        internal static string Common_name {
            get {
                return ResourceManager.GetString("Common name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding certificate.
        /// </summary>
        internal static string Error_adding_certificate {
            get {
                return ResourceManager.GetString("Error adding certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating certificate.
        /// </summary>
        internal static string Error_creating_certificate {
            get {
                return ResourceManager.GetString("Error creating certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing certificate.
        /// </summary>
        internal static string Error_removing_certificate {
            get {
                return ResourceManager.GetString("Error removing certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        internal static string Issuer {
            get {
                return ResourceManager.GetString("Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        internal static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization unit.
        /// </summary>
        internal static string Organization_unit {
            get {
                return ResourceManager.GetString("Organization unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFX file not found.
        /// </summary>
        internal static string PFX_file_not_found {
            get {
                return ResourceManager.GetString("PFX file not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key algorithm.
        /// </summary>
        internal static string Public_key_algorithm {
            get {
                return ResourceManager.GetString("Public key algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed certificate with thumbprint.
        /// </summary>
        internal static string Removed_certificate_with_thumbprint {
            get {
                return ResourceManager.GetString("Removed certificate with thumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string Serial_number {
            get {
                return ResourceManager.GetString("Serial number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to store in.
        /// </summary>
        internal static string store_in {
            get {
                return ResourceManager.GetString("store in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbprint.
        /// </summary>
        internal static string Thumbprint {
            get {
                return ResourceManager.GetString("Thumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from.
        /// </summary>
        internal static string Valid_from {
            get {
                return ResourceManager.GetString("Valid from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid to.
        /// </summary>
        internal static string Valid_to {
            get {
                return ResourceManager.GetString("Valid to", resourceCulture);
            }
        }
    }
}
